--Student functionality related data

--Student table
CREATE TABLE STUDENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    COUNTRY VARCHAR(30) NOT NULL,
    PERSONAL_NR BIGINT

 );

--Student data
INSERT INTO STUDENT ( NAME, SURNAME, COUNTRY, PERSONAL_NR) VALUES ( 'Pirmas', 'Test', 'Lithuania',262695216);
INSERT INTO STUDENT ( NAME, SURNAME, COUNTRY, PERSONAL_NR) VALUES ( 'Antras', 'Test', 'England',262654316);
INSERT INTO STUDENT ( NAME, SURNAME, COUNTRY, PERSONAL_NR) VALUES ( 'Trecias', 'Test', 'Latvia',261711216);
--Update auto increment as we inserted already 3 values
--ALTER TABLE STUDENT ALTER COLUMN ID RESTART WITH 5;