--Student functionality related data

--Student table
CREATE TABLE STUDENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL
 );

--Student data
INSERT INTO STUDENT ( NAME, SURNAME) VALUES ( 'Pirmas', 'Test');
INSERT INTO STUDENT ( NAME, SURNAME) VALUES ( 'Antras', 'Test');
INSERT INTO STUDENT ( NAME, SURNAME) VALUES ( 'Trecias', 'Test');